Repository gambitph/Stackable-e2e-tests, pull requests merged in 2021-09, with the labels that each got.

#230 Fix: typeblock delay failing tests
  .github/workflows/e2e-test-wp55.yml
  .github/workflows/e2e-test-wp56.yml
  .github/workflows/e2e-test-wp57.yml
  .github/workflows/e2e-test.yml
  cypress/integration/v2/blocks/accordion/index.js
  cypress/integration/v2/blocks/blockquote/index.js
  cypress/integration/v2/blocks/blog-posts/index.js
  cypress/integration/v2/blocks/blog-posts/other-tests.spec.js
  cypress/integration/v2/blocks/button/index.js
  cypress/integration/v2/blocks/card/index.js
  cypress/integration/v2/blocks/count-up/index.js
  cypress/integration/v2/blocks/cta/index.js
  cypress/integration/v2/blocks/expand/index.js
  cypress/integration/v2/blocks/feature-grid/index.js
  cypress/integration/v2/blocks/feature/index.js
  cypress/integration/v2/blocks/header/index.js
  cypress/integration/v2/blocks/heading/index.js
  cypress/integration/v2/blocks/icon-list/index.js
  cypress/integration/v2/blocks/icon/index.js
  cypress/integration/v2/blocks/image-box/index.js
  cypress/integration/v2/blocks/notification/index.js
  cypress/integration/v2/blocks/number-box/index.js
  cypress/integration/v2/blocks/pricing-box/index.js
  cypress/integration/v2/blocks/team-member/index.js
  cypress/integration/v2/blocks/testimonial/index.js
  cypress/integration/v2/blocks/text/index.js
  cypress/integration/v2/features/dynamic-content/helpers/fields.js
  cypress/integration/v2/features/dynamic-content/latest-page.spec.js
  cypress/integration/v2/features/dynamic-content/other-tests.spec.js
  cypress/integration/v2/features/global-settings/global-colors/index.js
  cypress/integration/v2/features/global-settings/global-typography/index.js
  cypress/integration/v3/blocks/test.spec.js
  cypress/support/stackable/helpers/modules.js
Labels: PR: Needs review, V3

#234 Fixes failing tests in `integration/v2/**/*.spec.js`
  cypress/integration/v2/features/dynamic-content/helpers/fields.js
  cypress/integration/v2/features/dynamic-content/latest-post.spec.js
  cypress/support/gutenberg/internals/block-snapshots.js
  cypress/support/stackable/commands/dynamic-content.js
  cypress/support/stackable/commands/setup.js
Labels: test by feature, v2

#235 Changed image position value
  cypress/support/stackable/helpers/modules.js
Labels: v2
