Repository gambitph/Stackable-e2e-tests, pull requests merged in 2021-08, with the labels that each got.

#210 trigger workflow run
  cypress/integration/v2/other-tests.spec.js
Labels: Github Actions

#156 Dynamic content: Current post
  cypress.json
  cypress/integration/v2/features/dynamic-content/current-post.spec.js
  cypress/support/gutenberg/commands/assertions.js
  cypress/support/gutenberg/commands/editor.js
  cypress/support/gutenberg/commands/readme.md
  cypress/support/gutenberg/commands/toolbar.js
  cypress/support/gutenberg/util.js
  cypress/support/stackable/commands/inspector.js
  cypress/support/stackable/commands/toolbar.js
  plugin.php
Labels: PR: Good to Merge

#190 Dynamic content: Other posts
  cypress/integration/v2/features/dynamic-content/other-posts.spec.js
  cypress/support/gutenberg/commands/assertions.js
  cypress/support/stackable/commands/toolbar.js
Labels: PR: Needs review

#187 Dynamic Content: Site Data
  cypress/integration/v2/features/dynamic-content/site-data.spec.js
  cypress/support/stackable/commands/toolbar.js
Labels: PR: Needs review

#215 test: multiple dynamic content in one line
  cypress/integration/v2/features/dynamic-content/other-tests.spec.js
  cypress/support/gutenberg/commands/toolbar.js
  cypress/support/gutenberg/util.js
  cypress/support/index.js
  cypress/support/stackable/commands/toolbar.js
Labels: PR: Needs review

#216 Test UGC & Sponsored links
  cypress/integration/v2/blocks/button/index.js
  cypress/integration/v2/blocks/card/index.js
  cypress/integration/v2/blocks/cta/index.js
  cypress/integration/v2/blocks/feature-grid/index.js
  cypress/integration/v2/blocks/feature/index.js
  cypress/integration/v2/blocks/header/index.js
  cypress/integration/v2/blocks/icon/index.js
  cypress/integration/v2/blocks/image-box/index.js
  cypress/integration/v2/blocks/notification/index.js
  cypress/integration/v2/blocks/pricing-box/index.js
  cypress/support/gutenberg/commands/assertions.js
  cypress/support/gutenberg/internals/block-snapshots.js
  cypress/support/stackable/helpers/index.js
Labels: PR: Reviewed w/ Comments

#218 Real hover events
  cypress/integration/v2/blocks/number-box/index.js
  cypress/integration/v2/features/global-settings/global-colors/index.js
  cypress/support/gutenberg/commands/assertions.js
  cypress/support/gutenberg/commands/editor.js
  cypress/support/gutenberg/commands/index.js
  cypress/support/gutenberg/commands/toolbar.js
  cypress/support/index.js
  cypress/support/stackable/commands/toolbar.js
  cypress/support/stackable/helpers/index.js
  package-lock.json
  package.json
Labels: enhancement, V3

#220 Moved selection commands inside `editor.js`
  cypress/support/gutenberg/commands/editor.js
  cypress/support/gutenberg/commands/index.js
  cypress/support/gutenberg/util.js
  cypress/support/stackable/commands/toolbar.js
Labels: enhancement, PR: Good to Merge

#224 Added delay to typeBlock
  cypress/support/stackable/commands/blocks.js
Labels: PR: Needs review

#226 Added delay to typeBlock
  cypress/support/gutenberg/commands/blocks.js
  cypress/support/stackable/commands/blocks.js
Labels: V3
